### ISSUE TITLE
请问怎么在博客项目中添加开源协议？

### ISSUE THREAD

**Issue by Siricee** [mogeko/blog#1]
您好，我看到您的博客中使用了CC BY-NC-SA 4.0协议，请问怎么在博客项目中添加开源协议？是在CC组织官网上添加链接并在根目录中添加一个License就完事了吗？。。这源码中没有任何改动，那怎么保护自己的版权。。搜了半天怎么添加开源协议也没有一个明确的说法，不知您是否可以告知。

**Comment by Siricee** [comment]
另外你的license.md是自己写的吗。。。

**Comment by mogeko** [comment]
在git仓库中添加license只是一个方面

按照[cc组织的说法](https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=zh)，更推崇的方式是在文章那个页面中声明使用cc4.0协议

![Screenshot_2019-05-11-21-31-01-116_Chrome](https://user-images.githubusercontent.com/26341224/57570405-1f137100-7434-11e9-8b0d-656f6755e482.png)

license.md 准确的说是我整理的，它里面的所有内容都来自[cc组织](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh#)，我一个字都不敢改。我还用链接附上了[cc4.0的具体协议内容](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode)应该是具备法律效应的

我也不是学法的，这样声明license有没有漏洞我也不知道，有什么说得不对的地方还请见谅😂😂

**Comment by Siricee** [comment]
好的 谢谢你！
